# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CountdownTimer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountdownTimer
  
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'CountdownTimerTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '1.2.0'
    pod 'Nimble', '7.0.3'
  end

  target 'CountdownTimerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
